### ISSUE TITLE
layout not displaying correctly on Safari MacOS

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Admin#14]
Cases list page:

![screen shot 2017-08-05 at 3 36 41 pm](https://user-images.githubusercontent.com/1994838/28998233-e7197812-79f3-11e7-9da0-2e3666da3595.png)

**Comment by StephenOTT** [comment]
Not working on Cases List, Services List, and Scenarios List.

**Comment by baddlan** [comment]
Fixed
