### ISSUE TITLE
Translation Tabs should so the language in the current UI's language

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Admin#26]
![screen shot 2017-08-05 at 6 31 42 pm](https://user-images.githubusercontent.com/1994838/28999209-62f207c0-7a0c-11e7-9ced-24a4e6355b06.png)

When in french UI, the english tab should have the french translation of "English".

Same for when in the English UI, the French Tab should have "French" not "Français"

![screen shot 2017-08-05 at 6 31 38 pm](https://user-images.githubusercontent.com/1994838/28999215-859bdfd0-7a0c-11e7-80ac-ff513ad44f6c.png)

**Comment by baddlan** [comment]
Fixed!
