### ISSUE TITLE
Cases: Case Statuses should have DateTime in datagrid + Sort order

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Admin#34]
currently the data grid does not have the data time.

![screen shot 2017-08-26 at 9 54 00 pm](https://user-images.githubusercontent.com/1994838/29746456-233f742a-8aa9-11e7-80a8-5b83bd067730.png)

Should have the date time.  

Also sort order should be DESC

**Comment by baddlan** [comment]
The Case Statuses are sorted but they all have the same Updated date.

**Comment by StephenOTT** [comment]
Should be sorted. By created date

________________________________
