### ISSUE TITLE
Add ability to add custom variable/property into a Service Scenario

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Admin#68]
Add ability to add a custom variable into the Configs column.

@baddlan

**Comment by baddlan** [comment]
@mario-digitalstate 
I added two UI fields to BPM scenarios to inject `custom_data` in the `config` property as follows:
```
...
"config": {
    "bpm": "camunda",
    "process_definition_key": "pothole-report",
    "custom_data": {
        "enable_custom_variables": true,
        "variable_value": {
            "aaa": "bbb"
        },
        "variable_name": "my_var"
    }
},
...
```

**Comment by marioprudhomme** [comment]
```
...
"config": {
    "bpm": "camunda",
    "process_definition_key": "pothole-report",
    "process_custom_data": {
        "enabled": true,
        "value": { // Always holds json object
            "aaa": "bbb"
        }
    },
},
...
```
variable name will be stored as a configuration under `app.bpm.variables.scenario_custom_data`, keeping the variable scope clean

`type` is ommitted for now to keep it simple, and assumed json. later on if we want to add types, the code will assume json if none provided, for backward compatibility.

**Comment by StephenOTT** [comment]
Notes:
The variable name is controlled through a MS config.

**Comment by StephenOTT** [comment]
@mario-digitalstate in your sample, you say "Always holds json object", does that mean a json array is not supported?

**Comment by marioprudhomme** [comment]
as long as its a camunda json type compatible value, it can be anything

**Comment by StephenOTT** [comment]
okay. 👍 looks good.

**Comment by marioprudhomme** [comment]
Backend is done. Once ui has been adjusted, this issue can be closed

**Comment by baddlan** [comment]
UI updated.
